## Service init

In [ ]:
from pychiver.saveandrestore import SaveAndRestore
sar = SaveAndRestore(service_url="http://jmasar.tn.esss.lu.se")

## Search available snapshots 

> For now, there is no SaveRestore (MASAR) API for the string search. Therefore the only way to get all snapshots is to browse the root folder for all unique IDs

In [2]:
print('=== Get Snapshots ')
test = sar.getSnapshots(configUniqueId='c2d7bf79-c6b9-4bb1-83be-c50a6ebc8776')

=== Get Snapshots
Getting available snapshots for config c2d7bf79-c6b9-4bb1-83be-c50a6ebc8776

In [29]:
for one in test.values():
    print('Snapshot name {} and uniqueID {}'.format(one.name, one.uniqueId))
    snapshotStoredValues = one.getStoredValues()
    snapshotComparisonResult = sar.compare(snapshot=one)

Snapshot name 107 kV and uniqueID fce5b9cd-a44d-4d64-b51f-89a40a4b0fc4
Snapshot name 65 kV and uniqueID c3f68792-1e80-45bb-bd19-b8942b809471

In [30]:
snapshotStoredValues

,PV Name,timestamp,secs_nanos,status_label,severity_label,stored_setpoint
0,RFQ-010:RFS-DIG-101:RFCtrlFFCalEGU,2021-06-08 16:16:43.982210636,1.623169e+09,NONE,NONE,"[0.025039373268850085, 0.10305522469998536, 0...."
1,RFQ-010:RFS-DIG-101:RFCtrlFFCalRaw,2021-06-08 16:16:43.982561111,1.623169e+09,NONE,NONE,"[0.0, 0.004974365234375, 0.009979248046875, 0...."

In [31]:
snapshotComparisonResult

,PV Name,timestamp,secs_nanos,status_label,severity_label,stored_setpoint,live_values,archived_values,delta
0,RFQ-010:RFS-DIG-101:RFCtrlFFCalEGU,2021-06-08 16:16:43.982210636,1.623169e+09,NONE,NONE,"[0.025039373268850085, 0.10305522469998536, 0....",None,NaN,NaN
1,RFQ-010:RFS-DIG-101:RFCtrlFFCalRaw,2021-06-08 16:16:43.982561111,1.623169e+09,NONE,NONE,"[0.0, 0.004974365234375, 0.009979248046875, 0....",None,NaN,NaN

In [16]:
print('===== All Config Sets')
confs = sar.getConfigurations()
for k, c in confs.items():
    print(k, c)

===== All Config Sets
[Test/test/ - 9ab3df03-575c-414e-af55-8522240eb08c] test/9ab3df03-575c-414e-af55-8522240eb08c
[Test/test-tf/ - 6d2ab609-6cc1-4f61-9d7e-24154a702f1a] test-tf/6d2ab609-6cc1-4f61-9d7e-24154a702f1a
[Test/TS2-LLRF2/ - fa85e844-61b5-44b7-a76a-54d762a95718] TS2-LLRF2/fa85e844-61b5-44b7-a76a-54d762a95718
[Test/aaaa/AnotherTest/ - 1f410074-fa9f-428f-bc81-1bffbc0b6dae] AnotherTest/1f410074-fa9f-428f-bc81-1bffbc0b6dae
[Test/marctest2/ - bbd5e234-e099-4ed7-a708-852dcc3958b4] marctest2/bbd5e234-e099-4ed7-a708-852dcc3958b4
[Test/TS2-LLRF1/ - a1dace8f-8613-4b5b-b0eb-7d868e4a3d94] TS2-LLRF1/a1dace8f-8613-4b5b-b0eb-7d868e4a3d94
[Test/ArekTest/ - 0e86c6c5-2cbe-4e07-99a8-76a44719e17a] ArekTest/0e86c6c5-2cbe-4e07-99a8-76a44719e17a
[Test/Arek2/ - 0dbd1d61-6f49-4d2b-95b4-f612e84ce31e] Arek2/0dbd1d61-6f49-4d2b-95b4-f612e84ce31e
[Test/Gabriel/ - 07b39b7e-bfd0-4301-9286-c95d5aa48a6c] Gabriel/07b39b7e-bfd0-4301-9286-c95d5aa48a6c
[Test/alfio-test/ - eeace19f-e811-46b9-aad1-f5e614574ece] alfio-test/eeace19f-e811-46b9-aad1-f5e614574ece
[Test/alfio2/ - 057d8f82-a7bf-4fb1-b74a-85e5c14717c6] alfio2/057d8f82-a7bf-4fb1-b74a-85e5c14717c6
[Test/2021-11-04 14:45:17/ - c1f28842-81e0-4ba3-b26e-fffd24d17c2b] 2021-11-04 14:45:17/c1f28842-81e0-4ba3-b26e-fffd24d17c2b
[Test/asdasdas/ - 85516f17-aeb4-499a-a12e-9bb4815a51fa] asdasdas/85516f17-aeb4-499a-a12e-9bb4815a51fa
[Test/TestArekTwo/ - 52fbf63f-627b-4b50-8668-73f6cd890d97] TestArekTwo/52fbf63f-627b-4b50-8668-73f6cd890d97
[Test/ISRC_Mag_PVs/ - 6ce50337-9f32-49af-8a31-b1deb7107506] ISRC_Mag_PVs/6ce50337-9f32-49af-8a31-b1deb7107506
[Migration 2019-11-07 15:35:25/all/MEBTQuad.bms/ - 0d20a9c1-8008-490a-944d-7d793329f195] MEBTQuad.bms/0d20a9c1-8008-490a-944d-7d793329f195
[Migration 2019-11-07 15:35:25/2021-01-25 19:05:22/ - 0eea8e69-3a9d-4916-b188-a05bb3a6fcc3] 2021-01-25 19:05:22/0eea8e69-3a9d-4916-b188-a05bb3a6fcc3
[Migration 2019-11-07 15:35:25/Operations/Golden/ISLEBT.bms/ - 27e7994f-ac0f-4006-a0dc-e62f9c2b8a27] ISLEBT.bms/27e7994f-ac0f-4006-a0dc-e62f9c2b8a27
[Migration 2019-11-07 15:35:25/Operations/ISrc-LEBT/Magnets.bms/ - 18b1fe6d-f29b-4d57-83c1-068a53a53f45] Magnets.bms/18b1fe6d-f29b-4d57-83c1-068a53a53f45
[Migration 2019-11-07 15:35:25/Operations/PHS/HeliumTanks.bms/ - 26af5c93-291a-4dd0-bef5-af7b8692248d] HeliumTanks.bms/26af5c93-291a-4dd0-bef5-af7b8692248d
[Migration 2019-11-07 15:35:25/Operations/TMCP/TMCP WCS/ - df2609a7-04a5-48d0-b7bc-65e4a36fc848] TMCP WCS/df2609a7-04a5-48d0-b7bc-65e4a36fc848
[Migration 2019-11-07 15:35:25/Operations/TICP/WCS_Parameters.bms/ - a57e27d7-ecb3-438e-a930-59b6b99a5a40] WCS_Parameters.bms/a57e27d7-ecb3-438e-a930-59b6b99a5a40
[Migration 2019-11-07 15:35:25/Operations/TICP/TICP_ColdBox.bms/ - c24079da-0872-4bdc-aa92-4004a2a75f27] TICP_ColdBox.bms/c24079da-0872-4bdc-aa92-4004a2a75f27
[Migration 2019-11-07 15:35:25/Operations/TICP/TS Parameters/ - 4fbcc192-6543-44b0-bb54-d153f73f2d31] TS Parameters/4fbcc192-6543-44b0-bb54-d153f73f2d31
[Migration 2019-11-07 15:35:25/ICSHWI-Maintain/ - 44197a21-e64a-457f-a370-0696f37dae19] ICSHWI-Maintain/44197a21-e64a-457f-a370-0696f37dae19
[Migration 2019-11-07 15:35:25/DTL4 ion pumps/ - edb5dad4-a437-40b3-8b73-59c8b36327fe] DTL4 ion pumps/edb5dad4-a437-40b3-8b73-59c8b36327fe
[MEBT-BPM/test-config/ - 30f97a88-9acd-46ee-95f3-0458941c91c6] test-config/30f97a88-9acd-46ee-95f3-0458941c91c6
[LLRF-TS2-2/StableOperation/ - bb69fa40-47bd-4877-a243-96d2816134db] StableOperation/bb69fa40-47bd-4877-a243-96d2816134db
[LLRF-TS2-2/test1/ - 98ef6cb8-97f2-4350-8408-9eee407d86b2] test1/98ef6cb8-97f2-4350-8408-9eee407d86b2
[LLRF-TS2-2/LLRF_TS2_2_1/ - d9db6143-9656-4004-b35f-5d9033603fea] LLRF_TS2_2_1/d9db6143-9656-4004-b35f-5d9033603fea
[LLRF-TS2-2/LLRF-System-2/ - 407136e6-d832-4f19-89bc-9ea8568c976c] LLRF-System-2/407136e6-d832-4f19-89bc-9ea8568c976c
[LLRF-TS2-2/StableOperationNew/ - 5a0768d0-1fa1-4ca2-98ad-f0fd81d73d63] StableOperationNew/5a0768d0-1fa1-4ca2-98ad-f0fd81d73d63
[LLRF-TS2-1/StableOperation/ - 5ef5c535-ab8f-4c8a-8583-0aeab5a0d2e8] StableOperation/5ef5c535-ab8f-4c8a-8583-0aeab5a0d2e8
[LLRF-TS2-1/LLRF20200319/ - 31eb4841-6806-4e80-ac9a-9a45919f159b] LLRF20200319/31eb4841-6806-4e80-ac9a-9a45919f159b
[LLRF-TS2-1/TestKrish/ - 4e9e7647-30e5-411a-ade4-d20a4243e3b0] TestKrish/4e9e7647-30e5-411a-ade4-d20a4243e3b0
[LLRF-TS2-1/LLRF-Sytem-1/ - 88449068-9e5b-4ddd-a6b4-cf669ac7e90b] LLRF-Sytem-1/88449068-9e5b-4ddd-a6b4-cf669ac7e90b
[LLRF-TS2-1/StableOperationNew/ - 50e22c14-9875-4e81-b8d2-65fa1eb21cf6] StableOperationNew/50e22c14-9875-4e81-b8d2-65fa1eb21cf6
[RFLPS-TS2/RFLPS_FIM_S01/ - 5294203b-0b99-4cc1-af4b-7872dcfb27a2] RFLPS_FIM_S01/5294203b-0b99-4cc1-af4b-7872dcfb27a2
[RFQ_Cond/RFS/Unused/ - 69014317-522c-43c6-8004-33bf4d4cc22a] Unused/69014317-522c-43c6-8004-33bf4d4cc22a
[RFQ_Cond/RFS/vacmon140/ - 7bc7b860-b294-469b-a6e9-2fe4322c6755] vacmon140/7bc7b860-b294-469b-a6e9-2fe4322c6755
[RFQ_Cond/RFS/test2/ - 334f1fe3-2629-41ff-a2b4-11918e4928da] test2/334f1fe3-2629-41ff-a2b4-11918e4928da
[SRF-TS2/LPSCavityInterlocks/ - 38607153-d548-4a38-acd3-a4ad5345acf1] LPSCavityInterlocks/38607153-d548-4a38-acd3-a4ad5345acf1
[SRF-TS2/GoodRFReadings/ - 1a23e597-311e-4566-95b0-15d347ce877a] GoodRFReadings/1a23e597-311e-4566-95b0-15d347ce877a
[SRF-TS2/VACCavityThresholds/ - 90e53f3c-177b-4668-b2e1-467756222897] VACCavityThresholds/90e53f3c-177b-4668-b2e1-467756222897
[SRF-TS2/Workstation Configurations/Philippe_Conditioning/ - 49c59044-786b-4a00-8059-07f38eccc143] Philippe_Conditioning/49c59044-786b-4a00-8059-07f38eccc143
[SRF-TS2/Workstation Configurations/Philippe_Cav4_Conditioning/ - 1cb24cf5-a9f0-4497-8399-8cd43ec099b8] Philippe_Cav4_Conditioning/1cb24cf5-a9f0-4497-8399-8cd43ec099b8
[CM-TS2/Cryomodules alarms limits/ - f45b2f3f-609d-468b-826e-255a25c2ad85] Cryomodules alarms limits/f45b2f3f-609d-468b-826e-255a25c2ad85
[DTL-010/RFLPS/GeneralConfig/ - e8a8fa73-f613-41f8-bd01-ed01c9e38ee0] GeneralConfig/e8a8fa73-f613-41f8-bd01-ed01c9e38ee0
[RFLPS-RFQ/FIM - RF system interlocks/ - 7b34c60f-2b4f-4168-b26a-f728a0e8dfe4] FIM - RF system interlocks/7b34c60f-2b4f-4168-b26a-f728a0e8dfe4
[RFLPS-RFQ/FIM - Unused channels/ - 10991a8d-a133-49e4-9f89-b5f4b052e702] FIM - Unused channels/10991a8d-a133-49e4-9f89-b5f4b052e702
[RFLPS-RFQ/FIM - Cavity interlocks/ - d0bd5fa5-8ad6-4839-9cf7-b8991985a35f] FIM - Cavity interlocks/d0bd5fa5-8ad6-4839-9cf7-b8991985a35f
[LLRF-RFQ/Closed Loop/ - 02ae7219-ff5c-47c6-9b11-ca9a1f57bb04] Closed Loop/02ae7219-ff5c-47c6-9b11-ca9a1f57bb04
[LLRF-RFQ/2021-03-17 17:54:25/ - 714a646c-3eb5-4573-86c6-efa1a82a0afe] 2021-03-17 17:54:25/714a646c-3eb5-4573-86c6-efa1a82a0afe
[LLRF-RFQ/VM output calibration/ - 08675977-6b94-4f43-8128-87b1d3ea1aef] VM output calibration/08675977-6b94-4f43-8128-87b1d3ea1aef
[LLRF-RFQ/Output calibration for different modulator voltage/ - c2d7bf79-c6b9-4bb1-83be-c50a6ebc8776] Output calibration for different modulator voltage/c2d7bf79-c6b9-4bb1-83be-c50a6ebc8776
[LLRF-RFQ/LLRF input channels/ - a26b7ec2-6da5-4a7f-9f3c-6f2753f55fb7] LLRF input channels/a26b7ec2-6da5-4a7f-9f3c-6f2753f55fb7
[LLRF-RFQ/ICS/LLRF Update/ - aa4a6478-15a7-42c8-9221-91f1e0ca58f5] LLRF Update/aa4a6478-15a7-42c8-9221-91f1e0ca58f5
[LEBT-Chopper/LEBT Chopper startup config/ - aab12b2c-c8a0-4e6e-8f20-31caeb72cb89] LEBT Chopper startup config/aab12b2c-c8a0-4e6e-8f20-31caeb72cb89
[Timing/Beam Production/TimingTables/ - 6605979b-8e77-4001-b9eb-c822ca436f1c] TimingTables/6605979b-8e77-4001-b9eb-c822ca436f1c
[Timing/EVR Delays/MEBT Chopper EVR/ - 7817bedb-8622-474d-85d9-40b62b578c95] MEBT Chopper EVR/7817bedb-8622-474d-85d9-40b62b578c95
[Timing/EVR Delays/Magnetron EVR/ - 69ea9201-7059-4c66-b5a3-d1687bb2a717] Magnetron EVR/69ea9201-7059-4c66-b5a3-d1687bb2a717
[Timing/EVR Delays/BCM EVR/ - e5a38d97-8784-429f-9091-606d4bb6d518] BCM EVR/e5a38d97-8784-429f-9091-606d4bb6d518
[Timing/EVR Delays/FC EVR/ - 4595c909-a12c-4d0c-bca9-39409d08829e] FC EVR/4595c909-a12c-4d0c-bca9-39409d08829e
[Timing/EVR Delays/BPM EVR/ - 738dbb95-0544-40ed-9da1-b3d5e92fd1f9] BPM EVR/738dbb95-0544-40ed-9da1-b3d5e92fd1f9
[Timing/EVR Delays/LEBT Chopper EVR/ - 28b333f9-7456-4d42-869b-8fedef225e89] LEBT Chopper EVR/28b333f9-7456-4d42-869b-8fedef225e89
[Operations/MEBT/MEBT_Quads/ - 50bd4c31-e3d7-4478-944a-a5d263be70ba] MEBT_Quads/50bd4c31-e3d7-4478-944a-a5d263be70ba
[Operations/MEBT/MEBT Steerers/MEBT steerers 3mA to MEBT FC Nov-26-2021/ - 32062458-bd9e-42c9-a239-618454e22a8a] MEBT steerers 3mA to MEBT FC Nov-26-2021/32062458-bd9e-42c9-a239-618454e22a8a
[Operations/ISrc-LEBT/ISrcLEBT/ - 99f3dcfd-8dcf-4b7a-a44b-365e9333e895] ISrcLEBT/99f3dcfd-8dcf-4b7a-a44b-365e9333e895
[Operations/ISrc-LEBT/Plasma/ - a6372232-3d57-46f9-b981-9dc0a0c8cc30] Plasma/a6372232-3d57-46f9-b981-9dc0a0c8cc30

## Get Snapshot details

> NOTE: getting snapshots direcly by their snapshotId is WIP, currently snapshots are available by a superior config set and then by name

In [3]:
snapshot = sar.getSnapshots(configUniqueId='50bd4c31-e3d7-4478-944a-a5d263be70ba')['MEBT quads day 1 (new)']
print(snapshot)

Getting available snapshots for config 50bd4c31-e3d7-4478-944a-a5d263be70ba
MEBT quads day 1 (new)/a030c243-0983-4674-b894-6c71237d3b7b

## Comparison

Compare snapshot to:
- live values (actual values)
- archived values (eg. at given point in time)
- another snapshot (WIP)

Return full comparison table (pandas) or simple flag True/False

In [6]:
comparisonResult = sar.compare(snapshot=snapshot, timeout=15)

In [7]:
comparisonResult

,PV Name,timestamp,secs_nanos,status_label,severity_label,stored_setpoint,live_values,archived_values,delta
0,MEBT-010:PwrC-PSQH-002:Cur-S,2021-11-23 15:38:58.191089392,1.637682e+09,NONE,NONE,119.50,119.50,NaN,0.00
1,MEBT-010:PwrC-PSQH-004:Cur-S,2021-11-23 15:40:34.211242199,1.637682e+09,NONE,NONE,29.21,29.21,NaN,0.00
2,MEBT-010:PwrC-PSQH-005:Cur-S,2021-11-23 15:41:42.182379246,1.637682e+09,NONE,NONE,35.15,0.00,NaN,35.15
3,MEBT-010:PwrC-PSQH-007:Cur-S,2021-11-19 15:17:20.207358122,1.637335e+09,NONE,NONE,0.00,0.00,NaN,0.00
4,MEBT-010:PwrC-PSQH-009:Cur-S,2021-11-19 15:17:20.207555771,1.637335e+09,NONE,NONE,0.00,0.00,NaN,0.00
5,MEBT-010:PwrC-PSQH-011:Cur-S,2021-11-19 15:17:20.207035303,1.637335e+09,NONE,NONE,0.00,0.00,NaN,0.00
6,MEBT-010:PwrC-PSQV-001:Cur-S,2021-11-23 15:38:40.177997828,1.637682e+09,NONE,NONE,99.70,99.70,NaN,0.00
7,MEBT-010:PwrC-PSQV-003:Cur-S,2021-11-23 15:39:48.629860640,1.637682e+09,NONE,NONE,73.20,73.20,NaN,0.00
8,MEBT-010:PwrC-PSQV-006:Cur-S,2021-11-23 15:41:02.613546610,1.637682e+09,NONE,NONE,50.10,0.00,NaN,50.10
9,MEBT-010:PwrC-PSQV-008:Cur-S,2021-11-19 15:17:20.207400799,1.637335e+09,NONE,NONE,0.00,0.00,NaN,0.00
10,MEBT-010:PwrC-PSQV-010:Cur-S,2021-11-19 15:17:20.207611799,1.637335e+09,NONE,NONE,0.00,0.00,NaN,0.00

In [8]:
sar.compareAndCheck(snapshot=snapshot, timeout=15)

## Restore

> NOTE as this is executed in the client side, it works under the condition of granted write access

In [ ]:
sar.restore(snapshot=snapshot, timeout=15)