In [1]:
from pychiver.saveandrestore import SaveAndRestore
sar = SaveAndRestore(service_url="http://jmasar.tn.esss.lu.se")

In [3]:
print('=== Get Snapshots ')
test = sar.getSnapshots(configUniqueId='c2d7bf79-c6b9-4bb1-83be-c50a6ebc8776')

=== Get Snapshots
Getting available snapshots for config c2d7bf79-c6b9-4bb1-83be-c50a6ebc8776

In [7]:
for one in test.values():
    storedValues = one.getStoredValues()
    result = sar.compare(snapshot=one)

In [8]:
storedValues

,PV Name,timestamp,secs_nanos,status_label,severity_label,stored_setpoint
0,RFQ-010:RFS-DIG-101:RFCtrlFFCalEGU,2021-06-08 16:16:43.982210636,1.623169e+09,NONE,NONE,"[0.025039373268850085, 0.10305522469998536, 0...."
1,RFQ-010:RFS-DIG-101:RFCtrlFFCalRaw,2021-06-08 16:16:43.982561111,1.623169e+09,NONE,NONE,"[0.0, 0.004974365234375, 0.009979248046875, 0...."

In [9]:
result

,PV Name,timestamp,secs_nanos,status_label,severity_label,stored_setpoint,live_values,delta
0,RFQ-010:RFS-DIG-101:RFCtrlFFCalEGU,2021-06-08 16:16:43.982210636,1.623169e+09,NONE,NONE,"[0.025039373268850085, 0.10305522469998536, 0....","[0.0, 0.250393732688501, 0.511561082955587, 0....","[0.025039373268850085, -0.14733850798851567, -..."
1,RFQ-010:RFS-DIG-101:RFCtrlFFCalRaw,2021-06-08 16:16:43.982561111,1.623169e+09,NONE,NONE,"[0.0, 0.004974365234375, 0.009979248046875, 0....","[0.0, 0.004974365234375, 0.009979248046875, 0....","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [2]:
print('===== All Configs')
confs = sar.getConfigurations()
for k, c in confs.items():
    print(k, c)

===== All Configs
[Migration 2019-11-07 15:35:25/all/MEBTQuad.bms/ - 0d20a9c1-8008-490a-944d-7d793329f195] MEBTQuad.bms/0d20a9c1-8008-490a-944d-7d793329f195
[Migration 2019-11-07 15:35:25/Operations/Golden/ISLEBT.bms/ - 27e7994f-ac0f-4006-a0dc-e62f9c2b8a27] ISLEBT.bms/27e7994f-ac0f-4006-a0dc-e62f9c2b8a27
[Migration 2019-11-07 15:35:25/Operations/ISrc-LEBT/Magnets.bms/ - 18b1fe6d-f29b-4d57-83c1-068a53a53f45] Magnets.bms/18b1fe6d-f29b-4d57-83c1-068a53a53f45
[Migration 2019-11-07 15:35:25/Operations/PHS/HeliumTanks.bms/ - 26af5c93-291a-4dd0-bef5-af7b8692248d] HeliumTanks.bms/26af5c93-291a-4dd0-bef5-af7b8692248d
[Migration 2019-11-07 15:35:25/Operations/TICP/WCS_Parameters.bms/ - a57e27d7-ecb3-438e-a930-59b6b99a5a40] WCS_Parameters.bms/a57e27d7-ecb3-438e-a930-59b6b99a5a40
[Migration 2019-11-07 15:35:25/Operations/TICP/TICP_ColdBox.bms/ - c24079da-0872-4bdc-aa92-4004a2a75f27] TICP_ColdBox.bms/c24079da-0872-4bdc-aa92-4004a2a75f27
[Migration 2019-11-07 15:35:25/Operations/TICP/TS Parameters/ - 4fbcc192-6543-44b0-bb54-d153f73f2d31] TS Parameters/4fbcc192-6543-44b0-bb54-d153f73f2d31
[Migration 2019-11-07 15:35:25/Operations/TMCP/TMCP WCS/ - df2609a7-04a5-48d0-b7bc-65e4a36fc848] TMCP WCS/df2609a7-04a5-48d0-b7bc-65e4a36fc848
[Migration 2019-11-07 15:35:25/2021-01-25 19:05:22/ - 0eea8e69-3a9d-4916-b188-a05bb3a6fcc3] 2021-01-25 19:05:22/0eea8e69-3a9d-4916-b188-a05bb3a6fcc3
[Migration 2019-11-07 15:35:25/ICSHWI-Maintain/ - 44197a21-e64a-457f-a370-0696f37dae19] ICSHWI-Maintain/44197a21-e64a-457f-a370-0696f37dae19
[RFLPS-TS2/RFLPS_FIM_S01/ - 5294203b-0b99-4cc1-af4b-7872dcfb27a2] RFLPS_FIM_S01/5294203b-0b99-4cc1-af4b-7872dcfb27a2
[LLRF-TS2-2/StableOperation/ - bb69fa40-47bd-4877-a243-96d2816134db] StableOperation/bb69fa40-47bd-4877-a243-96d2816134db
[LLRF-TS2-2/test1/ - 98ef6cb8-97f2-4350-8408-9eee407d86b2] test1/98ef6cb8-97f2-4350-8408-9eee407d86b2
[LLRF-TS2-2/LLRF_TS2_2_1/ - d9db6143-9656-4004-b35f-5d9033603fea] LLRF_TS2_2_1/d9db6143-9656-4004-b35f-5d9033603fea
[LLRF-TS2-1/StableOperation/ - 5ef5c535-ab8f-4c8a-8583-0aeab5a0d2e8] StableOperation/5ef5c535-ab8f-4c8a-8583-0aeab5a0d2e8
[LLRF-TS2-1/LLRF20200319/ - 31eb4841-6806-4e80-ac9a-9a45919f159b] LLRF20200319/31eb4841-6806-4e80-ac9a-9a45919f159b
[LLRF-TS2-1/TestKrish/ - 4e9e7647-30e5-411a-ade4-d20a4243e3b0] TestKrish/4e9e7647-30e5-411a-ade4-d20a4243e3b0
[Test/test/ - 9ab3df03-575c-414e-af55-8522240eb08c] test/9ab3df03-575c-414e-af55-8522240eb08c
[Test/test-tf/ - 6d2ab609-6cc1-4f61-9d7e-24154a702f1a] test-tf/6d2ab609-6cc1-4f61-9d7e-24154a702f1a
[Test/TS2-LLRF2/ - fa85e844-61b5-44b7-a76a-54d762a95718] TS2-LLRF2/fa85e844-61b5-44b7-a76a-54d762a95718
[Test/marctest2/ - bbd5e234-e099-4ed7-a708-852dcc3958b4] marctest2/bbd5e234-e099-4ed7-a708-852dcc3958b4
[Test/TS2-LLRF1/ - a1dace8f-8613-4b5b-b0eb-7d868e4a3d94] TS2-LLRF1/a1dace8f-8613-4b5b-b0eb-7d868e4a3d94
[Test/ArekTest/ - 0e86c6c5-2cbe-4e07-99a8-76a44719e17a] ArekTest/0e86c6c5-2cbe-4e07-99a8-76a44719e17a
[SRF-TS2/LPSCavityInterlocks/ - 38607153-d548-4a38-acd3-a4ad5345acf1] LPSCavityInterlocks/38607153-d548-4a38-acd3-a4ad5345acf1
[SRF-TS2/GoodRFReadings/ - 1a23e597-311e-4566-95b0-15d347ce877a] GoodRFReadings/1a23e597-311e-4566-95b0-15d347ce877a
[SRF-TS2/VACCavityThresholds/ - 90e53f3c-177b-4668-b2e1-467756222897] VACCavityThresholds/90e53f3c-177b-4668-b2e1-467756222897
[CM-TS2/Cryomodules alarms limits/ - f45b2f3f-609d-468b-826e-255a25c2ad85] Cryomodules alarms limits/f45b2f3f-609d-468b-826e-255a25c2ad85
[LLRF-RFQ/Closed Loop/ - 02ae7219-ff5c-47c6-9b11-ca9a1f57bb04] Closed Loop/02ae7219-ff5c-47c6-9b11-ca9a1f57bb04
[LLRF-RFQ/2021-03-17 17:54:25/ - 714a646c-3eb5-4573-86c6-efa1a82a0afe] 2021-03-17 17:54:25/714a646c-3eb5-4573-86c6-efa1a82a0afe
[LLRF-RFQ/VM output calibration/ - 08675977-6b94-4f43-8128-87b1d3ea1aef] VM output calibration/08675977-6b94-4f43-8128-87b1d3ea1aef
[LLRF-RFQ/Output calibration for different modulator voltage/ - c2d7bf79-c6b9-4bb1-83be-c50a6ebc8776] Output calibration for different modulator voltage/c2d7bf79-c6b9-4bb1-83be-c50a6ebc8776
[LLRF-RFQ/LLRF input channels/ - a26b7ec2-6da5-4a7f-9f3c-6f2753f55fb7] LLRF input channels/a26b7ec2-6da5-4a7f-9f3c-6f2753f55fb7
[MEBT-BPM/test-config/ - 30f97a88-9acd-46ee-95f3-0458941c91c6] test-config/30f97a88-9acd-46ee-95f3-0458941c91c6
[DTL-010/RFLPS/GeneralConfig/ - e8a8fa73-f613-41f8-bd01-ed01c9e38ee0] GeneralConfig/e8a8fa73-f613-41f8-bd01-ed01c9e38ee0
[RFQ_Cond/RFS/Unused/ - 69014317-522c-43c6-8004-33bf4d4cc22a] Unused/69014317-522c-43c6-8004-33bf4d4cc22a
[RFQ_Cond/RFS/vacmon140/ - 7bc7b860-b294-469b-a6e9-2fe4322c6755] vacmon140/7bc7b860-b294-469b-a6e9-2fe4322c6755
[RFQ_Cond/RFS/test2/ - 334f1fe3-2629-41ff-a2b4-11918e4928da] test2/334f1fe3-2629-41ff-a2b4-11918e4928da
[RFLPS-RFQ/FIM - RF system interlocks/ - 7b34c60f-2b4f-4168-b26a-f728a0e8dfe4] FIM - RF system interlocks/7b34c60f-2b4f-4168-b26a-f728a0e8dfe4
[RFLPS-RFQ/FIM - Unused channels/ - 10991a8d-a133-49e4-9f89-b5f4b052e702] FIM - Unused channels/10991a8d-a133-49e4-9f89-b5f4b052e702
[RFLPS-RFQ/FIM - Cavity interlocks/ - d0bd5fa5-8ad6-4839-9cf7-b8991985a35f] FIM - Cavity interlocks/d0bd5fa5-8ad6-4839-9cf7-b8991985a35f